version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: verikyc-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: verikyc
      POSTGRES_USER: verikyc_user
      POSTGRES_PASSWORD: verikyc_pass
    volumes:
      - verikyc-pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: verikyc-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: rajdeepthaosen7@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234567890
    depends_on:
      - postgres
    volumes:
      - verikyc-pgadmin:/var/lib/pgadmin

volumes:
  verikyc-pgdata:
  verikyc-pgadmin: